version: '3.8'
services:
 db:
   container_name: BenAwad-FullStack-React-GraphQL-Tut
   image: postgres
   restart: always
   environment:
     POSTGRES_DB: lireddit
     POSTGRES_USER: abdullah
     POSTGRES_PASSWORD: haris123
     PGDATA: /var/lib/postgresql/data
   ports:
     - "5432:5432"
   volumes:
     - db-data:/var/lib/postgresql/data

 pgadmin:
   container_name: pgadmin4_container
   image: dpage/pgadmin4:6.8
   restart: always
   environment:
     PGADMIN_DEFAULT_EMAIL: hsmeh.dev@gmail.com
     PGADMIN_DEFAULT_PASSWORD: admin
     PGADMIN_LISTEN_PORT: 80
   ports:
     - "8080:80"
   volumes:
     - pgadmin-data:/var/lib/pgadmin

#  cloudbeaver:
#    container_name: cloudbeaver
#    image: dbeaver/cloudbeaver:latest
#    restart: always
#    #  environment:
#    #    PGADMIN_DEFAULT_EMAIL: hsmeh.dev@gmail.com
#    #    PGADMIN_DEFAULT_PASSWORD: admin
#    #    PGADMIN_LISTEN_PORT: 80
#    ports:
#      - "8081:8978"
#    volumes:
#      - dbeaver-data:/var/cloudbeaver/workspace

volumes:
 db-data:
 pgadmin-data:
#  dbeaver-data: